apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "postgresql-operator.fullname" . }}-manager-role
  labels:
  {{- include "postgresql-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - postgresql.facets.cloud
  resources:
  - grants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgresql.facets.cloud
  resources:
  - grants/finalizers
  verbs:
  - update
- apiGroups:
  - postgresql.facets.cloud
  resources:
  - grants/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - postgresql.facets.cloud
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgresql.facets.cloud
  resources:
  - roles/finalizers
  verbs:
  - update
- apiGroups:
  - postgresql.facets.cloud
  resources:
  - roles/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "postgresql-operator.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: postgresql-operator
    app.kubernetes.io/part-of: postgresql-operator
  {{- include "postgresql-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "postgresql-operator.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "postgresql-operator.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'